import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_ui_auth/firebase_ui_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:teacher/core/common/views/under_construction_page.dart';
import 'package:teacher/core/extensions/context_extension.dart';
import 'package:teacher/core/services/injection_container.dart';
import 'package:teacher/features/auth/data/models/local_user_model.dart';
import 'package:teacher/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:teacher/features/auth/presentation/pages/sign_in_page.dart';
import 'package:teacher/features/auth/presentation/pages/sign_up_page.dart';
import 'package:teacher/features/dashboard/presentations/pages/dashboard.dart';
import 'package:teacher/features/on_boarding/data/datasource/on_boarding_local_data_source.dart';
import 'package:teacher/features/on_boarding/presentation/cubit/on_boarding_cubit.dart';
import 'package:teacher/features/on_boarding/presentation/pages/on_boarding_page.dart';

part 'router.main.dart';
